openapi: 3.0.0
info:
  contact:
    name: Kadaster
    email: dimitri.vanhees@kadaster.nl
    url: 'https://www.kadaster.nl'
  version: 0.0.1
  title: 'DUO RIO API'
servers:
  - url: 'https://.../api/v0'
paths:
  /bevoegd-gezagen:
    get:
      parameters:
        - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/page'
        - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/pageSize'
        - $ref: '#/components/parameters/denominatie'
        - $ref: '#/components/parameters/wetgeving'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/instellingSoort'
      responses:
        '200':
          $ref: '#/components/responses/BevoegdGezagen'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
      summary: 'Bevoegd gezagen collectie'
  '/bevoegd-gezagen/{id}':
    get:
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          $ref: '#/components/responses/BevoegdGezag'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '404':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/404'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
      summary: 'Bevoegd gezag resource'
  /onderwijsinstellingen:
    get:
      parameters:
        - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/page'
        - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/pageSize'
        - $ref: '#/components/parameters/denominatie'
        - $ref: '#/components/parameters/wetgeving'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/instellingSoort'
      responses:
        '200':
          $ref: '#/components/responses/Onderwijsinstellingen'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
      summary: 'Onderwijsinstellingen collectie'
  '/onderwijsinstellingen/{id}':
    get:
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          $ref: '#/components/responses/Onderwijsinstelling'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '404':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/404'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
      summary: 'Onderwijsinstelling resource'
components:
  parameters:
    id:
      name: id
      in: path
      description: Identifier
      required: true
      schema:
        type: string
    denominatie:
      name: denominatie
      in: query
      description: 'Filteren op `denominatie`'
      schema:
        type: string
    wetgeving:
      name: wetgeving
      in: query
      description: 'Filteren op `wetgeving`'
      schema:
        type: string
    type:
      name: type
      in: query
      description: 'Filteren op `type`'
      schema:
        type: string
    instellingSoort:
      name: instellingSoort
      in: query
      description: 'Filteren op `instellingSoort`'
      schema:
        type: string
  responses:
    BevoegdGezagen:
      description: OK.
      headers:
        X-Pagination-Page:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xPaginationPage'
        X-Pagination-Limit:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xPaginationLimit'
        X-Total-Count:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xTotalCount'
      content:
        application/hal+json:
          schema:
            required:
              - _embedded
              - _links
            type: object
            properties:
              _embedded:
                type: object
                properties:
                  bevoegdGezagen:
                    type: array
                    items:
                      $ref: '#/components/schemas/BevoegdGezag'
                required:
                  - bevoegdGezagen
              _links:
                type: object
                allOf:
                  - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/HalCollectionLinks'
    BevoegdGezag:
      description: OK.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/BevoegdGezag'
    Onderwijsinstellingen:
      description: OK.
      headers:
        X-Pagination-Page:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xPaginationPage'
        X-Pagination-Limit:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xPaginationLimit'
        X-Total-Count:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xTotalCount'
      content:
        application/hal+json:
          schema:
            required:
              - _embedded
              - _links
            type: object
            properties:
              _embedded:
                type: object
                properties:
                  onderwijsinstellingen:
                    type: array
                    items:
                      $ref: '#/components/schemas/Onderwijsinstelling'
                required:
                  - onderwijsinstellingen
              _links:
                type: object
                allOf:
                  - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/HalCollectionLinks'
    Onderwijsinstelling:
      description: OK.
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/Onderwijsinstelling'
  schemas:
    BevoegdGezag:
      type: object
      required:
        - _links
      properties:
        _links:
          type: object
          properties:
            self:
              allOf:
                - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/HalLink'
              description: 'Absolute link naar deze resource'
        denominatie:
          type: string
        wetgeving:
          type: string
        type:
          type: string
        instellingSoort:
          type: string
    Onderwijsinstelling:
      type: object
      required:
        - _links
      properties:
        _links:
          type: object
          properties:
            self:
              allOf:
                - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/HalLink'
              description: 'Absolute link naar deze resource'
        denominatie:
          type: string
        wetgeving:
          type: string
        type:
          type: string
        instellingSoort:
          type: string
