openapi: 3.0.0
info:
  version: 0.0.1
  title: Bestuurlijke Grenzen API
  contact:
    name: Kadaster
    email: dimitri.vanhees@kadaster.nl
    url: 'https://www.kadaster.nl'
servers:
  - url: 'https://.../..'
paths:
  /openbare-lichamen:
    get:
      summary: Collectie van openbare lichamen
      parameters:
      - $ref: '#/components/parameters/oin'
      - $ref: '#/components/parameters/cbsCode'
      - $ref: '#/components/parameters/aknId'
      - $ref: '#/components/parameters/type'
      - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/parameters.yaml#/acceptCrs'
      - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/page'
      - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OpenbareLichamen'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
  /openbare-lichamen/{oin}:
    get:
      summary: Enkel openbaar lichaam
      parameters:
      - $ref: '#/components/parameters/oin'
      responses:
        '200':
          $ref: '#/components/responses/OpenbaarLichaam'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
  /openbare-lichamen/_zoek:
    post:
      summary: Zoeken op openbare lichamen
      parameters:
      - $ref: '#/components/parameters/oin'
      - $ref: '#/components/parameters/cbsCode'
      - $ref: '#/components/parameters/aknId'
      - $ref: '#/components/parameters/type'
      - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/parameters.yaml#/acceptCrs'
      - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/parameters.yaml#/contentCrs'
      - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/page'
      - $ref: 'https://cdn.jsdelivr.net/gh/PDOK/open-api-specs/shared/parameters.yaml#/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OpenbareLichamen'
        '401':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/401'
        '403':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/403'
        '406':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/406'
        '503':
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/responses.yaml#/503'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                'gebied.geometrie':
                  type: object
                  description: Het veld waarop geografisch gezocht moet worden. In dit geval is dit het veld `gebied.geometrie`.
                  properties:
                    within:
                      allOf:
                      - $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/GeoJsonObject'
                      description: >-
                        Deze property bepaalt het type query. In dit geval
                        `within`, maar het kan ook `contains` of
                        `intersects` zijn. Het moet een valide GeoJSON `Point`
                        of `Polygon` object bevatten.
                      properties:
                        type: 
                          type: string
                          enum: [Point, Polygon]
components:
  parameters:
    type:
      name: type
      in: query
      description: Type openbaar lichaam
      required: false
      schema:
        type: string
        enum: [provincie, gemeente]
    oin:
      name: oin
      in: query
      description: OIN
      required: false
      schema:
        type: string
    cbsCode:
      name: cbsCode
      in: query
      description: CBS Code
      required: false
      schema:
        type: string
    aknId:
      name: aknId
      in: query
      description: AKN Identifier
      required: false
      schema:
        type: string
  responses:
    OpenbaarLichaam:
      description: OK.
      headers:
        Content-Crs:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/contentCrs'
      content:
        application/hal+json:
          schema:
            $ref: '#/components/schemas/OpenbaarLichaam'
    OpenbareLichamen:
      description: OK.
      headers:
        Content-Crs:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/contentCrs'
        X-Pagination-Page:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xPaginationPage'
        X-Pagination-Limit:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xPaginationLimit'
        X-Total-Count:
          $ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/headers.yaml#/xTotalCount'
      content:
        application/hal+json:
          schema:
            required: [_embedded, _links]
            type: object
            properties:
              _embedded:
                required:
                  - 'openbareLichamen'
                type: object
                properties:
                  openbareLichamen:
                    type: array
                    items:
                      $ref: '#/components/schemas/OpenbaarLichaam'
              _links:
                type: object
                allOf: [$ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/HalCollectionLinks']
  schemas:
    OpenbaarLichaam:
      type: object
      required:
        - type
        - oin
        - cbsCode
        - aknId
        - naam
        - _links
      properties:
        oin:
          type: string
        type:
          type: string
          enum: [provincie, gemeente]
        cbsCode:
          type: string
          nullable: true
        aknId:
          type: string
        naam:
          type: string
        _embedded:
          type: object
          properties:
            gebied:
              type: object
              properties:
                geometrie:
                  type: object
                  allOf: [$ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/GeoJsonObject']
        _links:
          required:
            - self
          type: object
          properties:
            self:
              allOf: [$ref: 'https://cdn.jsdelivr.net/gh/dvh/KP-APIs/oas-components/schemas.yaml#/HalLink']
              description: Absolute link naar huidige pagina
